-- Create Users Table
CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  provider_sub VARCHAR(255) NOT NULL UNIQUE,
  status TINYINT DEFAULT 1,
  email VARCHAR(255) NOT NULL UNIQUE,
  display_name VARCHAR(100) NOT NULL,
  group_id INT DEFAULT NULL,
  role VARCHAR(50) DEFAULT 'member',
  joined_at BIGINT DEFAULT UNIX_TIMESTAMP(),
  mod_at BIGINT DEFAULT UNIX_TIMESTAMP(),
  last_login BIGINT DEFAULT 0,
  auth VARCHAR(50) DEFAULT 'google',
  settings JSON DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Create Sessions Table
CREATE TABLE IF NOT EXISTS sessions (
  id INT AUTO_INCREMENT PRIMARY KEY,
  session_key CHAR(64) NOT NULL UNIQUE,
  user_id INT NOT NULL,
  created_at BIGINT DEFAULT UNIX_TIMESTAMP(),
  expires_at BIGINT NOT NULL,
  status TINYINT DEFAULT 1,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
